version: '3'

services:
  web:
    image: futuredays/alleganwizard
    build: .
    ports:
      - "8001:8000"
    depends_on:
      - postgres
    deploy:
        replicas: 1
    networks:
      - webnetwork
  postgres:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    volumes:
      - /root/site-data/alleganwizard:/var/lib/postgresql/data
    deploy:
        replicas: 1
        placement:
            constraints: [node.role == manager]
    networks:
      - webnetwork

networks:
    webnetwork:
