version: '3'

# Conventions for compatibility with SwarmBuilder:
#   - The application service must be named 'web'.
#   - The database must define a placement constraint of [node.role == manager]
#   - The database should define a volume to map its data folder to the hosts '/root/site-data/[projectName]' folder.
#       That folder will be automatically created as long as you use the name 'projectName' to name this service stack:
#       i.e. swarmbuilder deploy mySwarm --compose-file ./docker-compose.yml --stack-name projectName

#   - Ports should NOT be mapped here. The http-proxy is the only container on the swarm with published ports.
#       All other containers communicate on the 'http-proxy' overlay network and do not need to publish specific ports.

services:
  web:
    image: futuredays/alleganwizard
    build: .
    depends_on:
      - postgres
    deploy:
        replicas: 1
        labels:
            - "traefik.enable=true"
            - "traefik.backend=web"
            - "traefik.frontend.rule=Host:test.smirksoftware.com"
            - "traefik.port=80"
            - "traefik.docker.network=http-proxy"
  postgres:
    image: postgres:10-alpine
    volumes:
      - /root/site-data/alleganwizard:/var/lib/postgresql/data
    deploy:
        replicas: 1
        placement:
            constraints: [node.role == manager]

networks:
  default:
    external:
      name: http-proxy