version: '3'

# Conventions for compatibility with SwarmBuilder:
#   - The application service must be named 'web'.
#   - The database must define a placement constraint of [node.role == manager]
#   - The database should define a volume to map its data folder to the hosts '/root/site-data/[projectName]' folder.
#       This folder must exist before the docker container is started.
#   - Ports should NOT be mapped here. The nginx-proxy is the only publicly-accessible container on the swarm.
#       All other containers communicate on Docker's internal network.
#   - A network need not be defined unless multiple networks are required.  A default network will be created
#       when this compose file is run.

services:
  web:
    image: futuredays/alleganwizard
    build: .

    # Ports are exposed here for development only.
    ports:
      - "8001:8000"
    depends_on:
      - postgres
    deploy:
        replicas: 1
  postgres:
    image: postgres:10-alpine
    # Database ports should NOT be exposed publicly
#    ports:
#      - "5432:5432"
    volumes:
      - /root/site-data/alleganwizard:/var/lib/postgresql/data
    deploy:
        replicas: 1
        placement:
            constraints: [node.role == manager]
