apiVersion: v1
kind: ReplicationController
metadata:
  name: postgres
  namespace: tellient
spec:
  replicas: 1
  selector:
    app: postgres
  template:
    metadata:
      name: postgres
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: mdillon/postgis:9.6
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data-volume
      volumes:
      - name: postgres-data-volume
        hostPath:
          # directory location on host
          path: /root/postgres-tellient-data-volume
